# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_logged_in_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
