# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradvertisementviewed',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
